---
# Deploy Ceph via Cephadm. Create EC profiles, CRUSH rules, pools and keys.
- name: Import Cephadm deploy playbook
  import_playbook: cephadm-deploy.yml

- name: Import Cephadm commands pre playbook
  import_playbook: cephadm-commands-pre.yml

- name: Import Cephadm EC profiles playbook
  import_playbook: cephadm-ec-profiles.yml

- name: Import Cephadm crush rules playbook
  import_playbook: cephadm-crush-rules.yml

- name: Import Cephadm pools playbook
  import_playbook: cephadm-pools.yml

- name: Import Cephadm keys playbook
  import_playbook: cephadm-keys.yml

- name: Import Cephadm commands post playbook
  import_playbook: cephadm-commands-post.yml
