---
- name: Define Ceph pools
  gather_facts: false
  hosts: mons
  become: true
  tags:
    - cephadm
    - cephadm-keys
  tasks:
    - name: Apply Cephadm pools role
      ansible.builtin.import_role:
        name: stackhpc.cephadm.pools
