---
- name: Define Ceph EC profiles
  gather_facts: false
  hosts: mons
  become: true
  tags:
    - cephadm
    - cephadm-ec-profiles
  tasks:
    - name: Apply Cephadm EC profiles role
      ansible.builtin.import_role:
        name: stackhpc.cephadm.ec_profiles
