---
collections:
  - name: stackhpc.cephadm
    version: 1.19.3
  # NOTE: Pinning pulp.squeezer to 0.0.13 because 0.0.14+ depends on the
  # pulp_glue Python library being installed.
  - name: pulp.squeezer
    version: 0.0.13
